version: "3"
services:
  app:
    build: ./app
    volumes:
      - /app_data
      - socket:/tmp
    environment:
      - BM_ADMIN_NAME=admin
      - BM_ADMIN_PASSWORD=password
    command: uwsgi --ini /app/app.ini

  web:
    image: nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web/static/:/var/www/:ro
      - socket:/tmp

volumes:
  socket: